-- SELECTING SUPNR, SUPNAME , SUPADDRESS OF THOSE WHERE R1.SUPRNR< R2.SUPNR-
-- THEREBY FETCHING MORE EXPERIENCED SUPPLIERS , SINCE SUPPLIERS WITH SMALL SUPNR
-- WLD HAVE REGISTERED EARLIER AND WILL HAVE MORE EXPERIENCE
use project;
select r1.SUPNR,r2.SUPNAME,r1.SUPADDRESS
from SUPPLIER r1, supplier r2
where r1.prodnr=r2.prodnr
and (r1.supnr<r2.supnr)