-- SELECTING PRODUCT NAMES WHERE THE SUPPLIER IS " DUCKERING "
SELECT P.PRODNR,P.PRODNAME, R.SUPNR, R.SUPNAME, R.SUPADDRESS
From SUPPLIER AS R INNER JOIN PRODUCT AS P
ON (P.PRODNR = R.PRODNR)
 WHERE R.SUPNAME ="Duckering"