-- 7.
-- This part defines a Common Table Expression (CTE) named HUNGRYFOODS. --
-- It selects the recipe name (as RECIPENAME), raƟng ID (as RATING), and
-- feedback text (as FEEDBACK) from the tables RECIPE (aliased as R), RATINGS (aliased as RA),
-- and FEEDBACK (aliased as F).
-- IT BASICALLY FINDS THE TOTAL_RATINGS FOR EACH RECIPENAME
WITH HUNGRYFOODS AS(SELECT R.FOODNAME AS RECIPENAME,RA.RATINGID AS RATING,
F.FEEDBACKTEXT AS FEEDBACK
FROM RECIPE R, RATINGS RA, FEEDBACK f
WHERE RA.RECIPEID=R.RECIPEID AND
R.RECIPEID=F.RECIPEID)
SELECT RECIPENAME,SUM(RATING) AS TOTAL_RATINGS
FROM HUNGRYFOODS
GROUP BY RECIPENAME
